### ISSUE TITLE
Add reports filtering by CampaignId

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/MAVN.Service.AdminAPI#57]
Expose new optional filter by CampaignId in reporting endpoints (POST ​/api​/Reports and GET ​/api​/Reports​/exportToCsv) and pass this property to new filter property implemented in OpenMAVN/MAVN.Service.Reporting#19

**Comment by lAnubisl** [comment]
https://github.com/LykkeCity/Lykke.HttpClientGenerator/pull/16
https://github.com/OpenMAVN/MAVN.Service.AdminAPI/pull/61
https://github.com/OpenMAVN/MAVN.Service.Reporting/pull/22
